// Composition elements (`<video>`, `<image>`) name their media by library
// path — the project's assets/ folder is its library, so `assets/aroll.mp4`
// is "aroll.mp4". An `<img>` inside HTML content is the exception: it only
// loads from an absolute path, so those go through `ASSETS`. `./repo.js`
// holds this clone's path — generated by running ./setup.sh once after
// cloning (it is not committed).
import { REPO } from "./repo.js";

export const ASSETS = `${REPO}/assets`;
