// Media `src` is resolved against the OS, not this file, so asset paths must
// be absolute. `./repo.js` holds this clone's path — generated by running
// ./setup.sh once after cloning (it is not committed).
import { REPO } from "./repo.js";

export const ASSETS = `${REPO}/assets`;
